### ISSUE TITLE
${shlibs:Depends} not defined

### ISSUE THREAD

**Issue by JPeisach** [wasta-linux/cinnamon-layout#1]
When building ubuntucinnamon-layout:

dpkg-gencontrol: warning: Depends field of package ubuntucinnamon-layout: substitution variable ${shlibs:Depends} used, but is not defined

**Comment by rik-shaw** [comment]
I think that is a standard warning given when building locally. It is a required piece to resolve dependencies as far as I understand.

I have noticed that using "debuild -b" to build locally gives different lintian warnings than when it autobuilds at launchpad, for example. So I don't understand fully but again it seems to be a standard part of any debian package?

**Comment by rik-shaw** [comment]
I did a bit of looking and it seems that it could possibly be removed. I'll give it a try when I am able.

**Comment by rik-shaw** [comment]
I removed ${shlibs:Depends} from debian/control. I think it isn't necessary even though it was part of default control templates.
